![New York City schoolbus](schoolbus.jpg)

Photo by [Jannis Lucas](https://unsplash.com/@jannis_lucas) on [Unsplash](https://unsplash.com).
<br>

Every year, American high school students take SATs, which are standardized tests intended to measure literacy, numeracy, and writing skills. There are three sections - reading, math, and writing, each with a **maximum score of 800 points**. These tests are extremely important for students and colleges, as they play a pivotal role in the admissions process.

Analyzing the performance of schools is important for a variety of stakeholders, including policy and education professionals, researchers, government, and even parents considering which school their children should attend. 

You have been provided with a dataset called `schools.csv`, which is previewed below.

You have been tasked with answering three key questions about New York City (NYC) public school SAT performance.

In [4]:
# Re-run this cell 
import pandas as pd

# Read in the data
schools = pd.read_csv("datasets/schools.csv")

# Preview the data
schools.head()

,school_name,borough,building_code,average_math,average_reading,average_writing,percent_tested
0,"New Explorations into Science, Technology and ...",Manhattan,M022,657,601,601,NaN
1,Essex Street Academy,Manhattan,M445,395,411,387,78.9
2,Lower Manhattan Arts Academy,Manhattan,M445,418,428,415,65.1
3,High School for Dual Language and Asian Studies,Manhattan,M445,613,453,463,95.9
4,Henry Street School for International Studies,Manhattan,M056,410,406,381,59.7

**1- Which NYC schools have the best math results?**

In [13]:
# find the minimum best math score
best_math_score = 800 * 80 / 100
print(best_math_score)

# find the best math schools
best_math_schools = schools[schools['average_math'] >= best_math_score][['school_name', 'average_math']].sort_values('average_math', ascending= False)
print(best_math_schools.head())

640.0
                                           school_name  average_math
88                              Stuyvesant High School           754
170                       Bronx High School of Science           714
93                 Staten Island Technical High School           711
365  Queens High School for the Sciences at York Co...           701
68   High School for Mathematics, Science, and Engi...           683

**2- What are the top 10 performing schools based on the combined SAT scores?**

In [19]:
# find the best schools based on the combined SAT scores 
schools['total_SAT'] = schools['average_math'] + schools['average_reading'] + schools['average_writing']
top_10_schools = schools.sort_values('total_SAT', ascending= False)[['school_name', 'total_SAT']].iloc[0:10]
print(top_10_schools)

                                           school_name  total_SAT
88                              Stuyvesant High School       2144
170                       Bronx High School of Science       2041
93                 Staten Island Technical High School       2041
174  High School of American Studies at Lehman College       2013
333                        Townsend Harris High School       1981
365  Queens High School for the Sciences at York Co...       1947
5                       Bard High School Early College       1914
280                     Brooklyn Technical High School       1896
45                       Eleanor Roosevelt High School       1889
68   High School for Mathematics, Science, and Engi...       1889

**3- Which single borough has the largest standard deviation in the combined SAT score?**

In [37]:
# find the borough with the largest standard deviation
largest_std_dev = schools.groupby('borough').agg(
    total_SAT = ('total_SAT', 'sum'),
    num_schools = ('borough', 'count'), 
    average_SAT = ('total_SAT', 'mean'),
    std_SAT = ('total_SAT', 'std')
).round(2).sort_values('std_SAT', ascending= False).iloc[0:1]
print(largest_std_dev)

           total_SAT  num_schools  average_SAT  std_SAT
borough
Manhattan     119272           89      1340.13   230.29